#-------------------------#
#       Parameters        #
#-------------------------#
# Input DSM path (expected format: "<folder_1>/<folder_2>/<file>.<[tif/tiff]>")
dsm_path : "outputs_cars_pre_event/cars_dsm_pre_event.tif"
# Output directory path (if the directory doesn't exist, create it)
output_dir : "outputs_bulldozer_pre_event"

#-------------------------#
#         Options         #
#-------------------------#
# If True, generates the DHM (DSM - DTM) in the output directory 
generate_dhm : True
# If null, the output DTM resolution will be the same as the input DSM (float value in meter)
output_resolution : null
# If null, bulldozer will use the maximum number of available CPU on your system
nb_max_workers : 16

#-------------------------#
#    Advanced settings    #
#-------------------------#

# Foreground max object width (in meter)
max_object_width : 16
# If True, this flag allows snapping DTM values above the DSM to the DSM values in order to satisfy the property that DTM is always below the DSM.
check_intersection: False
# Minimum valid height value, None or a float value. If null this parameter is ignored
min_valid_height: 0.0
# If null, the nodata value will be extracted from the input DSM (float value or nan)
no_data : null
# If True, keep the intermediate results
developper_mode : False
# If True, keep the intermediate DTM at each level of the pyramid
keep_inter_dtm : False

#-------------------------#
# Bulldozer core settings #
#-------------------------#
# /!\ Modify those data at your own risk (it is suggested to keep the default values) /!\

# DetectDisturbedAreasAndFill part
slope_threshold : 2.0
# numnumber of evaluated axis. Vertical and horizontal if true else vertical, horizontal and diagonals.
four_connexity : True

# DtmExtraction part
uniform_filter_size : 3
prevent_unhook_iter : 10
num_outer_iter : 50
num_inner_iter : 10
mp_tile_size : 1500
